[tools]
python = "3.13.7"

[env]
PYTHONPATH = "{{config_root}}"
_.path = ["{{config_root}}/.venv/bin"]

[tasks.setup-python]
description = "Create a local virtualenv and install python dependencies"
run ="""
python -m venv .venv
.venv/bin/pip install --upgrade pip
pip install uv
uv add west
"""

[tasks.setup-zephyr]
description = "Create a local virtualenv and install python dependencies"
depends = ["setup-python"]
run ="""
west init -l .
west update
west zephyr-export
west packages pip --install
cd ../zephyr
west sdk install
"""

[tasks.flash-metro]
description = "Depends on west, builds and flashes fw to Metro"
run ="""
west build -p always -b adafruit_metro_rp2350/rp2350b/m33 --shield adafruit_2_8_tft_touch_v2 applications/app
cp build/zephyr/zephyr.uf2 /media/$USER/RP2350
"""

[settings]
python.uv_venv_auto = true
